#!/usr/bin/env bash
#-- Requirements ---------------------------------------------------------------------------------------------------------------
command -v jq     >/dev/null 2>&2 || { echo >&2 "jq is required but is not available, aborting...";     exit 1; }
command -v docker >/dev/null 2>&2 || { echo >&2 "docker is required but is not available, aborting..."; exit 1; }

#-- Imported Variables ---------------------------------------------------------------------------------------------------------
project_name=$(cat < ./scripts/scripts_configuration.json | jq -r '.project_name')
project_owner=$(cat < ./scripts/scripts_configuration.json | jq -r '.project_owner')

target=$1
if [ -z "${target}" ]; then ls config/secrets && read -rp "Which environment would you like to target? Type your full answer here and press enter: " target; fi

network_name=$(cat < "./config/secrets/${target}/script_secrets.json"  | jq -r '.secrets.network_name')

database_url=$(cat < "./config/secrets/${target}/script_secrets.json" | jq -r '.secrets.database_url')
database_port=$(cat < "./config/secrets/${target}/script_secrets.json" | jq -r '.secrets.database_port')
database_name=$(cat < "./config/secrets/${target}/script_secrets.json" | jq -r '.secrets.database_name')
database_user=$(cat < "./config/secrets/${target}/script_secrets.json"  | jq -r '.secrets.database_user')
database_schema=$(cat < "./config/secrets/${target}/script_secrets.json" | jq -r '.secrets.database_schema')
database_password=$(cat < "./config/secrets/${target}/script_secrets.json" | jq -r '.secrets.database_password')
database_ssl_mode=$(cat < "./config/secrets/${target}/script_secrets.json" | jq -r '.secrets.database_ssl_mode')

run_local=$(cat < "./config/secrets/${target}/script_secrets.json"  | jq -r '.secrets.run_local')
if [ "${run_local}" == "true" ]; then  database_url="${project_owner}_${project_name}_ephemeral_${database_schema}_postgres"; fi

#-- Assume image exists --------------------------------------------------------------------------------------------------------
image_tag="${project_owner}/${project_name}_manufacturize"

dump_artifact_directory=tmp

#-- Create container for ephemeral use -----------------------------------------------------------------------------------------
container_name="${project_owner}_${project_name}_ephemeral_dumplicate"
sudo docker run                                                               \
  --name "${container_name}"                                                  \
  --network "${network_name}"                                                 \
  --env TARGET="${target}"                                                    \
  --env PSQL_HOST="${database_url}"                                           \
  --env PSQL_PORT="${database_port}"                                          \
  --env PSQL_DBNAME="${database_name}"                                        \
  --env PSQL_SSLMODE="${database_ssl_mode}"                                   \
  --env PSQL_USER="${database_user}"                                          \
  --env PSQL_PASS="${database_password}"                                      \
  --volume $PWD/${dump_artifact_directory}:/output                            \
  --interactive --tty                                                         \
  --rm                                                                        \
  "${image_tag}"

sudo chmod -R 700 ./${dump_artifact_directory}/*
sudo chown -R ${USER}:${USER} ./${dump_artifact_directory}/*