#!/usr/bin/env bash
#-- Requirements ---------------------------------------------------------------------------------------------------------------
command -v jq     >/dev/null 2>&2 || { echo >&2 "jq is required but is not available, aborting...";     exit 1; }
command -v docker >/dev/null 2>&2 || { echo >&2 "docker is required but is not available, aborting..."; exit 1; }

#-- Imported Variables ---------------------------------------------------------------------------------------------------------
project_name=$(cat < ./scripts/scripts_configuration.json | jq -r '.project_name')
project_owner=$(cat < ./scripts/scripts_configuration.json | jq -r '.project_owner')

target=$1
if [ -z "${target}" ]; then ls config/secrets && read -rp "Which environment would you like to target? Type your full answer here and press enter: " target; fi

network_name=$(cat < "./config/secrets/${target}/script_secrets.json"  | jq -r '.secrets.network_name')

database_url=$(cat < "./config/secrets/${target}/script_secrets.json" | jq -r '.secrets.database_url')
database_port=$(cat < "./config/secrets/${target}/script_secrets.json" | jq -r '.secrets.database_port')
database_name=$(cat < "./config/secrets/${target}/script_secrets.json" | jq -r '.secrets.database_name')
database_user=$(cat < "./config/secrets/${target}/script_secrets.json"  | jq -r '.secrets.database_user')
database_schema=$(cat < "./config/secrets/${target}/script_secrets.json" | jq -r '.secrets.database_schema')
database_password=$(cat < "./config/secrets/${target}/script_secrets.json" | jq -r '.secrets.database_password')
database_ssl_mode=$(cat < "./config/secrets/${target}/script_secrets.json" | jq -r '.secrets.database_ssl_mode')

run_local=$(cat < "./config/secrets/${target}/script_secrets.json"  | jq -r '.secrets.run_local')
if [ "${run_local}" == "true" ]; then  database_url="${project_owner}_${project_name}_ephemeral_${database_schema}_postgres"; fi

#-- Assume image exists --------------------------------------------------------------------------------------------------------
image_tag="migrate/migrate:v4.10.0"
migrations_directory=schemas/${database_schema}

#-- Create container for ephemeral use -----------------------------------------------------------------------------------------
container_name="${project_owner}_${project_name}_ephemeral_migrate"
sudo docker run                                                               \
  --name "${container_name}"                                                  \
  --network "${network_name}"                                                 \
  --volume $PWD/${migrations_directory}:/migrations:ro                        \
  --interactive --tty                                                         \
  --rm                                                                        \
  "${image_tag}"                                                              \
    -source=file://migrations                                                 \
    -database postgres://${database_user}:${database_password}@${database_url}:${database_port}/${database_name}?sslmode=${database_ssl_mode} \
    -verbose                                                                  \
    up