#!/usr/bin/env bash
#-- Requirements ---------------------------------------------------------------------------------------------------------------
command -v jq     >/dev/null 2>&2 || { echo >&2 "jq is required but is not available, aborting...";     exit 1; }
command -v docker >/dev/null 2>&2 || { echo >&2 "docker is required but is not available, aborting..."; exit 1; }

#-- Imported Variables ---------------------------------------------------------------------------------------------------------
project_name=$(cat < ./scripts/scripts_configuration.json | jq -r '.project_name')
project_owner=$(cat < ./scripts/scripts_configuration.json | jq -r '.project_owner')

#-- Create container for ephemeral use -----------------------------------------------------------------------------------------
image_tag="${project_owner}/${project_name}_restorify"
sudo docker build                                                             \
  --file dockerfiles/restorify.docker                                         \
  --tag "${image_tag}"                                                        \
  ./
